//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarDetails = new HashSet<CarDetails>();
            this.CarDetailPhotos = new HashSet<CarDetailPhotos>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime BoughtDate { get; set; }
        public int BoughtPrice { get; set; }
        public int SalePrice { get; set; }
        public System.DateTime PublishDate { get; set; }
        public Nullable<int> SoldPrice { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public bool isDeleted { get; set; }
        public bool isSold { get; set; }
        public bool isPayed { get; set; }
        public string PayedNumber { get; set; }
        public int UserID { get; set; }
        public bool isRemoved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarDetails> CarDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarDetailPhotos> CarDetailPhotos { get; set; }
        public virtual Users Users { get; set; }
    }
}
