//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetails
    {
        public int ID { get; set; }
        public int BrandID { get; set; }
        public int SeriesID { get; set; }
        public int ModelID { get; set; }
        public int Year { get; set; }
        public int FuelID { get; set; }
        public int GearID { get; set; }
        public string Kilometer { get; set; }
        public int CaseID { get; set; }
        public int Power { get; set; }
        public int Capacity { get; set; }
        public int TractionID { get; set; }
        public string Color { get; set; }
        public int PlateID { get; set; }
        public int CarID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Car Car { get; set; }
        public virtual Case Case { get; set; }
        public virtual Fuel Fuel { get; set; }
        public virtual Gear Gear { get; set; }
        public virtual Model Model { get; set; }
        public virtual Plate Plate { get; set; }
        public virtual Series Series { get; set; }
        public virtual Traction Traction { get; set; }
    }
}
