//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetailPhotos
    {
        public int ID { get; set; }
        public int CarID { get; set; }
        public string PhotoLink { get; set; }
        public bool isMainPhoto { get; set; }
        public string PhotoName { get; set; }
        public string PhotoKey { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
