//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarSalesEntities : DbContext
    {
        public CarSalesEntities()
            : base("name=CarSalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Case> Case { get; set; }
        public virtual DbSet<Fuel> Fuel { get; set; }
        public virtual DbSet<Gear> Gear { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<ModelSeries> ModelSeries { get; set; }
        public virtual DbSet<Plate> Plate { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<SeriesBrand> SeriesBrand { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Traction> Traction { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarDetails> CarDetails { get; set; }
        public virtual DbSet<CarDetailPhotos> CarDetailPhotos { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
